import { describe, expect, it } from 'vitest'
import { TOOLS, TOOL_NAMES, toolSpec, type ToolName } from '@/lib/assistant/tools'
import {
  can,
  isScopedAction,
  SYSTEM_ROLE_NAMES,
  SYSTEM_ROLE_PERMISSIONS,
  type Actor,
  type PermissionKey,
  type Subject,
  type SystemRoleName,
} from '@/lib/permissions'

/**
 * §4.6's central claim is that the assistant cannot do anything the person
 * could not do by clicking. That claim rests on two things being true, and
 * both are checked here without a database, a session or a model.
 *
 *   1. Every tool that changes something names the permission it needs.
 *      A tool added later with no entry fails the first block, so the
 *      failure mode is a red test rather than an unguarded capability.
 *
 *   2. For every tool, role and subject, the tool's reachability is exactly
 *      can()'s answer for the action it declares. Generated by iterating the
 *      product, not enumerated by hand — an enumerated list only covers the
 *      cases someone thought of, which is never the case that bites.
 */

const ORG = '11111111-1111-1111-1111-111111111111'
const OTHER_ORG = '22222222-2222-2222-2222-222222222222'
const ME = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'
const SOMEONE_ELSE = 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'

function actorFor(role: SystemRoleName): Actor {
  return {
    id: ME,
    orgId: ORG,
    permissions: new Set<PermissionKey>(SYSTEM_ROLE_PERMISSIONS[role]),
  }
}

/** The four relationships a subject can have to the actor. */
const SUBJECTS: ReadonlyArray<{ label: string; subject: Subject }> = [
  {
    label: 'mine',
    subject: { orgId: ORG, createdByUserId: ME, attendeeIds: [ME] },
  },
  {
    label: "someone else's, I attend",
    subject: { orgId: ORG, createdByUserId: SOMEONE_ELSE, attendeeIds: [ME, SOMEONE_ELSE] },
  },
  {
    label: "someone else's, I do not attend",
    subject: { orgId: ORG, createdByUserId: SOMEONE_ELSE, attendeeIds: [SOMEONE_ELSE] },
  },
  {
    label: 'another organisation',
    subject: { orgId: OTHER_ORG, createdByUserId: ME, attendeeIds: [ME] },
  },
]

/**
 * Tools that need no §3 permission, and why. Written out so that adding a
 * tool without an action is a deliberate entry here rather than an omission
 * nobody notices.
 */
const NO_PERMISSION_NEEDED: Record<string, string> = {
  list_team: 'the team roster is visible to everyone in the org',
  notify_user: 'anyone can send a colleague a direct message by clicking',
}

describe('the tool catalogue', () => {
  it('has a spec for every name and a name for every spec', () => {
    expect(TOOLS.map((t) => t.name).sort()).toEqual([...TOOL_NAMES].sort())
    for (const name of TOOL_NAMES) expect(toolSpec(name)?.name).toBe(name)
  })

  it('names a permission for every tool, or records why not', () => {
    for (const tool of TOOLS) {
      if (tool.action === null) {
        expect(
          NO_PERMISSION_NEEDED[tool.name],
          `${tool.name} needs no permission — say why in NO_PERMISSION_NEEDED`,
        ).toBeTypeOf('string')
      } else {
        expect(NO_PERMISSION_NEEDED[tool.name]).toBeUndefined()
      }
    }
  })

  it('describes when to call each tool, not just what it does', () => {
    // Descriptions are the model's only guidance on triggering. A one-liner
    // gets a tool that fires at the wrong moment.
    for (const tool of TOOLS) expect(tool.description.length).toBeGreaterThan(80)
  })

  it('declares schemas the API will accept in strict mode', () => {
    for (const tool of TOOLS) {
      const schema = tool.input_schema
      expect(schema.type).toBe('object')
      // strict mode rejects a schema that leaves extra keys open.
      expect(schema.additionalProperties).toBe(false)
      for (const key of schema.required) {
        expect(Object.keys(schema.properties), `${tool.name}.${key}`).toContain(key)
      }
      // Every property is described, or the model is guessing at its meaning.
      for (const prop of Object.values(schema.properties)) {
        expect(prop.description.length).toBeGreaterThan(0)
      }
    }
  })

  it('only stages the tools that change something', () => {
    const writes = TOOLS.filter((t) => t.effect === 'write').map((t) => t.name)
    expect(writes.sort()).toEqual(
      (
        [
          'cancel_meeting',
          'notify_user',
          'reassign_meeting',
          'reschedule_meeting',
        ] satisfies ToolName[]
      ).sort(),
    )
  })
})

/**
 * The reachability matrix, generated rather than listed: every tool against
 * every seeded role against every subject relationship.
 */
describe('no tool reaches past can()', () => {
  for (const tool of TOOLS) {
    for (const role of SYSTEM_ROLE_NAMES) {
      const actor = actorFor(role)

      if (tool.action === null) {
        it(`${tool.name} · ${role} · needs no permission`, () => {
          expect(NO_PERMISSION_NEEDED[tool.name]).toBeTypeOf('string')
        })
        continue
      }

      const action = tool.action

      if (!isScopedAction(action)) {
        it(`${tool.name} · ${role}`, () => {
          expect(can(actor, action)).toBe(actor.permissions.has(action))
        })
        continue
      }

      for (const { label, subject } of SUBJECTS) {
        it(`${tool.name} · ${role} · ${label}`, () => {
          const allowed = can(actor, action, subject)

          // Cross-tenant is denied for everyone, Owner included. No tool has
          // a route around the tenant gate because no tool has a route to
          // authorization other than this function.
          if (subject.orgId !== actor.orgId) {
            expect(allowed).toBe(false)
            return
          }

          // Otherwise the answer must be the elevated grant, or the own
          // grant over something the actor actually owns — restated here
          // independently of can()'s implementation so a change to either
          // side has to be justified against the other.
          const owns =
            subject.createdByUserId === actor.id ||
            (action === 'meeting.view' || action === 'transcript.view'
              ? (subject.attendeeIds?.includes(actor.id) ?? false)
              : false)

          const expected = ELEVATED[action].some((k) => actor.permissions.has(k))
            ? true
            : OWN[action].some((k) => actor.permissions.has(k)) && owns

          expect(allowed).toBe(expected)
        })
      }
    }
  }
})

const ELEVATED = {
  'meeting.create': ['meeting.create.any'],
  'meeting.edit': ['meeting.edit.any'],
  'meeting.delete': ['meeting.delete.any'],
  'meeting.view': ['meeting.view.all'],
  'transcript.view': ['transcript.view.all'],
} as const satisfies Record<string, readonly PermissionKey[]>

const OWN = {
  'meeting.create': ['meeting.create.own'],
  'meeting.edit': ['meeting.edit.own'],
  'meeting.delete': ['meeting.delete.own'],
  'meeting.view': ['meeting.view.own'],
  'transcript.view': ['transcript.view.own'],
} as const satisfies Record<string, readonly PermissionKey[]>
